name = "reddit-facts-proxy"
main = "workers/redditFactsWorker.js"
compatibility_date = "2024-10-03"

routes = [
  { pattern = "api.ecys.xyz/api/reddit-facts", zone_id = "720195a2cd6b2172cc64d725f440056f" }
]
